### ISSUE TITLE
Init should return a bool

### ISSUE THREAD

**Issue by harbaum** [Ryzee119/tusb_xinput#11]
The init function should return a bool (and probably false if it failed to init).

This is currently not checked in usbh.c, so it currently doesn't hurt. But in the future it may be checked and cause your driver to fail loading.

Also, please mark unused parameters like the rhport in open as unused like adding "(void) rhport;" to the begin of the function.

Other than that: The driver works for me :-) Thanks a lot!

**Comment by Ryzee119** [comment]
Thanks! youre right

Closed by  https://github.com/Ryzee119/tusb_xinput/commit/0f9cbc3953431c602376d7e7f3c7a6ff2149c544
