### ISSUE TITLE
How can I send custom commands? (Logitech G920 Steering Wheel)

### ISSUE THREAD

**Issue by guighub** [Ryzee119/tusb_xinput#13]
Hi, I've been using this repository to try and translate Xbox inputs from a Logitech steering wheel to work on Nintendo Switch as a wired controller, and so far I've managed to print out the inputs using your example in the readme. The one problem I'm having is that the steering wheel I'm using has autocenter enabled by default, meaning the wheel will always try to move towards the center position. This makes turning the wheel really really hard in gameplay. I've looked into [some open source programs](https://github.com/nightmode/logitech-g29/blob/c69abb32a107dc1b9b02c30b590ac66213adceee/code/index.js#L374) that support this wheel and a couple of them seem to send the command `0xf5, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00` to disable the autocenter. I tried this with your code and it didn't seem to do anything. Is there any special format I need to use to get custom Xinput/Xbox commands to work in this library?

Here's how I've been sending commands to the wheel:
```c++
static const uint8_t data[] = { 0xf5, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };

tuh_xinput_send_report(dev_addr, instance, data, sizeof(data));
while (usbh_edpt_busy(dev_addr, xid_itf->ep_out))
{
  tuh_task();
}
```

**Comment by Ryzee119** [comment]
That looks about right to me. Perhaps it's not right for that wheel?

You'd need to use Wireshark or similar to monitor USB traffic assuming you can trigger in on a PC to find the command.

**Comment by guighub** [comment]
Yeah, I monitored the USB traffic on my Raspberry Pi and later found out the wheel is actually sent a command to remount as an HID device, and *that* device is used for force feedback. The command is likely unrelated to the Xinput mode and instead the HID mode, so I'll have to figure out the correct way to send the command through HID.
