### ISSUE TITLE
Help requested

### ISSUE THREAD

**Issue by jimnarey** [Ryzee119/tusb_xinput#4]
Hi - thank you for posting this (and for answering some of my questions a while ago on the ogx360 project).

I've made the modifications to TinyUSB as suggested. I'm not sure where the xinput_host.c and xinput_host.h need to be included. Do they need to be placed in the TinyUSB tree somewhere and included in one or more of the files there or should they be included in my project.

Thanks.

**Comment by Ryzee119** [comment]
the repo has all been updated for the latest upsteam tinyUSB.

Hopefully these problems should be alleviated
