### ISSUE TITLE
Can't build example in Arduino

### ISSUE THREAD

**Issue by Willyarma** [Ryzee119/tusb_xinput#8]
Hi, I'm getting this build error...

RPI_Pico_device_info:319:1: error: 'usbh_class_driver_tconst' does not name a type; did you mean 'usbh_class_driver_t'?
  319 | usbh_class_driver_t const* usbh_app_driver_get_cb(uint8_t* driver_count){
      | ^~~~~~~~~~~~~~~~~~~~~~~~
      | usbh_class_driver_t

The compiler seems to be ignoring the space.
It compiles if I remove the code and braces after, but obviously that isnt going to work.

I'm using a RP2040 device with Adafruit_TinyUSB which in turn uses Pico-PIO-USB
I've got the host functions working with HID devices, getting button reports etc..
I didnt realise the XBox controller was not HID so wanted to try and add this.

Is there anything I can do to fix this?

**Comment by Ryzee119** [comment]
Weird. Make sure it's actually a space character and not something weird

You could probably remove that const keyword anyway

**Comment by Willyarma** [comment]
This appears to work...

usbh_class_driver_t const* usbh_app_driver_get_cb(uint8_t* driver_count);

usbh_class_driver_t const* usbh_app_driver_get_cb(uint8_t* driver_count)
{
    *driver_count = 1;
    return &usbh_xinput_driver;
}

however the linker complains about not being able to find usbh_xinput_driver, this is because CFG_TUH_XINPUT isnt defined.

Your instructions say to add CFG_TUH_XINPUT=1 into tusb_option.h (which isnt so easy in arduino) but im not sure exactly where to put it in the file, can you give an example?

As a hack i added:
#define CFG_TUH_XINPUT 1
to xinput_host.c to get it to compile which it does now.

It appears to work. Thanks for creating this library

**Comment by Ryzee119** [comment]
Awesome. I haven't tried tinyusb on Arduino so I'm glad you got it working 🙂
